on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  TF_ACC: "1"
  GO111MODULE: "on"
  LXD_GENERATE_CLIENT_CERTS: "true"
  LXD_ACCEPT_SERVER_CERTIFICATE: "true"

name: Test
jobs:
  acc-standalone:
    runs-on: ${{ matrix.os }}
    name: standalone (${{ matrix.channel }}, ${{ matrix.os }})
    env:
      LXD_CEPH_CLUSTER: "ceph"
      LXD_CEPH_CEPHFS: "cephfs"
      LXD_CEPH_CEPHOBJECT_RADOSGW: "http://127.0.0.1"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
        channel:
          - 5.21/stable
          - 5.21/edge
          - 6/stable
          - 6/edge
        include:
          - channel: 5.0/stable
            os: ubuntu-22.04
          - channel: 5.0/edge
            os: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'go.mod'

      - name: Setup LXD from ${{ matrix.channel }} channel
        run: |
          sudo snap refresh lxd --channel=${{ matrix.channel }} --cohort=+ || sudo snap install lxd --channel=${{ matrix.channel }} --cohort=+
          sudo snap refresh --hold=8h
          sudo lxd waitready --timeout 60
          sudo lxd init --auto --network-port=8443 --network-address=localhost
          sudo chmod 777 /var/snap/lxd/common/lxd/unix.socket

          # LVM from the snap is buggy so use the external one from the runner machine.
          if command -v lvm > /dev/null; then
            sudo snap set lxd lvm.external=true
            sudo systemctl reload snap.lxd.daemon.service
          fi

          # Add HTTPS remote.
          lxc remote add localhost "$(lxc config trust add --name lxd-terraform-provider --quiet)"

      - name: Setup MicroCeph
        uses: canonical/lxd/.github/actions/setup-microceph@8a8e4c8ad05da9d5345e08a2821e530adff7b8a8 # stable-5.21
        with:
          osd-count: "1"

      - name: Download minio/mc
        uses: canonical/lxd/.github/actions/download-minio@8a8e4c8ad05da9d5345e08a2821e530adff7b8a8 # stable-5.21
        if: ${{ startsWith(matrix.channel, '5.21/') || matrix.channel == '6/stable' }}

      - name: Configure MinIO
        if: ${{ startsWith(matrix.channel, '5.21/') || matrix.channel == '6/stable' }}
        run: |
          mkdir -p /opt/minio
          mv "$(go env GOPATH)/bin/minio" /opt/minio/
          mv "$(go env GOPATH)/bin/mc" /opt/minio/

          # Set the snap config key for minio and reload LXD to have it take effect.
          sudo snap set lxd minio.path=/opt/minio
          sudo systemctl reload snap.lxd.daemon

      - name: Configure OVN
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes \
            ovn-host \
            ovn-central \
            bind9-dnsutils \
            jq

          sudo ovs-vsctl set open_vswitch . \
            external_ids:ovn-remote=unix:/var/run/ovn/ovnsb_db.sock \
            external_ids:ovn-encap-type=geneve \
            external_ids:ovn-encap-ip=127.0.0.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_wrapper: false

      - name: Run acceptance tests
        run: make test

  acc-cluster:
    runs-on: ${{ matrix.os }}
    name: cluster (${{ matrix.channel }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
        channel:
          - 5.21/candidate
          - 5.21/edge
          - 6/candidate
          - 6/edge
        include:
          - channel: 5.0/stable
            os: ubuntu-22.04
          - channel: 5.0/edge
            os: ubuntu-22.04
          - channel: 5.21/stable
            os: ubuntu-22.04
          - channel: 6/stable
            os: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'go.mod'

      - name: Setup LXD cluster
        uses: ./.github/actions/cluster
        with:
          cluster-name: acctest
          cluster-size: 2
          instance-type: virtual-machine
          lxd-version: ${{ matrix.channel }}
          enable-ovn: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_wrapper: false

      - name: Run acceptance tests
        run: make test
        env:
          LXD_TEST_SKIP_VMS: "true"

  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          cache: false
          go-version-file: 'go.mod'

      - name: Run GoReleaser in build mode to test all release platforms
        uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7.2.2
        with:
          args: build --snapshot

  lint:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'go.mod'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: latest

      - run: make fmtcheck
      - run: make vet
      - run: make static-analysis
